### PR TITLE
modules: hal_silabs: add SE Manager API for SoCs using the SE subsystem 

### PR DESCRIPTION
**Pull request by l-alfred**
Origin: Silicon Labs Gecko SDK
URL: https://www.silabs.com/products/development-tools/software/simplicity-studio
Version: 3.1.0
Purpose: Add SE Manager high-level APIs for SoCs using the SE subsystem
License: Zlib
Maintained-by: External

Origin: Original
Purpose: Add zephyr bindings to the SE Manager API.

There is a PR for the main files at [#38936](https://github.com/zephyrproject-rtos/zephyr/pull/38936)

Signed-off-by: Steven Lemaire <steven.lemaire@zii.aero>

### CODE REVIEW

**Comment by mbolivar-nordic** [comment]
@chrta since @galak is not with the project now, can you please take a look?

**Review by chrta — APPROVED** [review]
I have not tested this, but the structure and README changes look good.

**Comment by mbolivar-nordic** [comment]
@stephanosio what should we do about merging this? I don't have privileges and this HAL update seems to be blocking merge of https://github.com/zephyrproject-rtos/zephyr/pull/38936, which is approved

**Comment by stephanosio** [comment]
> @stephanosio what should we do about merging this? I don't have privileges and this HAL update seems to be blocking merge of [zephyrproject-rtos/zephyr#38936](https://github.com/zephyrproject-rtos/zephyr/pull/38936), which is approved

Merged

**Pull request merged**
