### PR TITLE
se_manager: update sources

### PR DESCRIPTION
**Pull request by lpawelcz**
This PR updates the Secure Element manager sources. It also removes the duplicate directory of the se_manager component.

This is needed for Entropy support for EFR32MG24 in Zephyr.

### CODE REVIEW

**Comment by mrfuchs** [comment]
Thanks for this PR. I was working on a similar update.

However, don't you (unintentionally) revert 77a0605 that added Zephyr bindings for the SE Manager?

**Comment by fkokosinski** [comment]
> However, don't you (unintentionally) revert [77a0605](https://github.com/zephyrproject-rtos/hal_silabs/commit/77a060590c00b5c69814b4743ba9ae74e8dbc702) that added Zephyr bindings for the SE Manager?

Hi @mrfuchs, it indeed looks like the bindings that were added in the mentioned commit are reverted by this PR. I did a little investigation, and:
* they were added as a part of adding the SE-based entropy driver here: https://github.com/zephyrproject-rtos/zephyr/pull/38936
* the entropy driver doesn't rely on these bindings being present
* these bindings were based on GSDK 3.1.0. GSDK now uses CMSISv2, which complicates the process of re-adding these bindings a bit
* I couldn't find an SoC that relies on these bindings being present

IMO if none of the Zephyr boards/drivers/SoCs rely on them, dropping them shouldn't be a problem, because there's no point in maintaining something that isn't used by anything in Zephyr.

**Comment by mrfuchs** [comment]
Thank you for the clarification, @fkokosinski.

**Review by fkokosinski — APPROVED** [review]

**Comment by fkokosinski** [comment]
It looks like #21 bumped the SE Manager sources, so this PR is no longer needed. Closing.

**Pull request closed without merging**
