### PR TITLE
modules: hal_silabs: Add Silabs Gecko HAL for EFR32BG13P SoCs

### PR DESCRIPTION
**Pull request by mnkp**
Origin: Silicon Labs Gecko SDK
URL: https://www.silabs.com/products/development-tools/software/simplicity-studio
Version: v5.6.0
Purpose: Add support for Silicon Labs EFR32BG13 SoCs
License: Zlib
Maintained-by: External

### CODE REVIEW

**Comment by mnkp** [comment]
@chrta please review.

**Comment by galak** [comment]
is there a zephyr PR that uses this?

**Comment by mnkp** [comment]
> is there a zephyr PR that uses this?

I've a branch that adds support for BRD4104A board, which is using EFR32BG13P SoC. All works well, but I still need to update the board documentation, the .rst file. I'll create a PR later this week.

**Comment by mnkp** [comment]
@galak Could we merge this PR? [#22423](https://github.com/zephyrproject-rtos/zephyr/pull/22423) provides SoC and board support.

**Pull request merged**
