### PR TITLE
Added EFR32FG23 device

### PR DESCRIPTION
**Pull request by yishai1999**
Origin: Simplicity SDK
License: Zlib
URL: https://github.com/SiliconLabs/simplicity_sdk
Commit: 19a4476b12e9e827cbdd89c58141494fea188a67
Version: 2024.6.2
Purpose: HAL for EFR32ZG23 Silicon Labs device

### CODE REVIEW

**Comment by yishai1999** [comment]
@jhedberg I can't seem to find how to request a review so I'm just tagging you.

I want to start using the EFR32ZG23 in zephyr so I decided to add the HAL here.

This is my first time opening a PR in a HAL repo so if I did something wrong LMK.
Also, is there a reason we don't just add all the devices supported by simplicity? I can expand this PR to do that if there's no problem with that.

**Comment by asmellby** [comment]
Thanks for your contribution! I expect the reason the patch script didn't work for you is that it's written for macOS, which uses BSD sed, which has a slightly different syntax for in-place edits than GNU sed.

When it comes to device support, we want to fully automate the addition of new devices and boards, including the device tree content in the main tree. Until we get automation in place, we're keeping the device support limited to the devices that are actively used, in order to limit the amount of manual labor to maintain it. Since setting up Zephyr by default pulls in all the vendor HALs, we're being good citizens by waiting to commit HAL support until we have/are close to having support in the main tree, which keeps the repo size down. So I suggest keeping to only adding support for the device families you need for now.

**Review by asmellby — CHANGES_REQUESTED** [review]
On second thought: Please add the changes to `import_simplicity_sdk.py` as a separate commit in this PR, so the script is up to date for the next user.

**Review by asmellby — APPROVED** [review]

**Review by jerome-pouiller — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Comment by jhedberg** [comment]
Before we merge this, could you please follow the process outlined here: https://docs.zephyrproject.org/latest/develop/modules.html#process-for-submitting-changes-to-existing-modules

I.e. create a pull request in the main tree that references this pull request. Once the main tree PR passes CI and has been approved, we can proceed with merging this PR (after which you update the main tree PR to point at the correct ref).

**Comment by yishai1999** [comment]
> Before we merge this, could you please follow the process outlined here: https://docs.zephyrproject.org/latest/develop/modules.html#process-for-submitting-changes-to-existing-modules
> 
> I.e. create a pull request in the main tree that references this pull request. Once the main tree PR passes CI and has been approved, we can proceed with merging this PR (after which you update the main tree PR to point at the correct ref).

Done! https://github.com/zephyrproject-rtos/zephyr/pull/82737

**Comment by jhedberg** [comment]
> Done! [zephyrproject-rtos/zephyr#82737](https://github.com/zephyrproject-rtos/zephyr/pull/82737)

The purpose of this process is for the new module changes to be tested by the main tree CI and/or reviewers. In this case it means that this should be accompanied by an actual board definition (and drivers, if a board isn't enough) that use these new files in the HAL tree.

**Comment by yishai1999** [comment]
> > Done! [zephyrproject-rtos/zephyr#82737](https://github.com/zephyrproject-rtos/zephyr/pull/82737)
> 
> The purpose of this process is for the new module changes to be tested by the main tree CI and/or reviewers. In this case it means that this should be accompanied by an actual board definition (and drivers, if a board isn't enough) that use these new files in the HAL tree.

Got it. I'll start working on that.

**Pull request merged**
