### PR TITLE
Add librail support for efr32xg1x devices

### PR DESCRIPTION
**Pull request by yonsch**
Add librail support for efr32xg1x devices

### CODE REVIEW

**Comment by yonsch** [comment]
ref: https://github.com/zephyrproject-rtos/zephyr/pull/61107

**Comment by yonsch** [comment]
@carlescufi @fkokosinski I should add, when compiling this the compiler complained about floating point ABI ("zephyr_pre0 uses VFP register arguments, * does not"), so I had to compile the app with `-DCONFIG_FPU=n`. I'm not sure if this is because Silabs changed their compilation flags or something else. If this is a blocker I'll add a DNM until I get to the bottom of this.

**Comment by carlescufi** [comment]
> @carlescufi this PR introduces new blobs. I'm not aware if this has been approved by the TSC (nothing in the notes; no binary blob issue etc.?)

Agreed, added a DNM, this PR is blocked by:
https://github.com/zephyrproject-rtos/zephyr/issues/61109

**Review by carlescufi — CHANGES_REQUESTED** [review]
Blocking until https://github.com/zephyrproject-rtos/zephyr/issues/61109 goes through the TSC

**Comment by carlescufi** [comment]
> @carlescufi @fkokosinski I should add, when compiling this the compiler complained about floating point ABI ("zephyr_pre0 uses VFP register arguments, * does not"), so I had to compile the app with `-DCONFIG_FPU=n`. I'm not sure if this is because Silabs changed their compilation flags or something else. If this is a blocker I'll add a DNM until I get to the bottom of this.

This is @fkokosinski's call.

**Comment by fkokosinski** [comment]
> @carlescufi @fkokosinski I should add, when compiling this the compiler complained about floating point ABI ("zephyr_pre0 uses VFP register arguments, * does not"), so I had to compile the app with `-DCONFIG_FPU=n`. I'm not sure if this is because Silabs changed their compilation flags or something else. If this is a blocker I'll add a DNM until I get to the bottom of this.

@yonsch Ideally we would want the compiler to throw warnings at the user. Because this is a blob, there's no real way of influencing with which flags it was compiled, so this really sounds like we should just set `CONFIG_FPU` to `n` when using RAIL on Series 1 SoCs in Kconfig.

**Comment by fkokosinski** [comment]
> Doesn't this happen with the 2's?

@yonsch I'm not sure what you edited my comment instead of replying in a separate one, but I've just tested building `samples/bluetooth/observer` sample on `efr32bg22_brd4184a` (Series 2 SoC) from the current Zephyr main branch and it compiled without any warnings.

**Review by fkokosinski — CHANGES_REQUESTED** [review]

**Comment by yonsch** [comment]
> > Doesn't this happen with the 2's?
> 
> @yonsch I'm not sure what you edited my comment instead of replying in a separate one, but I've just tested building `samples/bluetooth/observer` sample on `efr32bg22_brd4184a` (Series 2 SoC) from the current Zephyr main branch and it compiled without any warnings.

Sorry, I must have accidentally pressed edit instead of copy reply.
In that case, disabling FPU only if the 1x series is used seems fine.

**Comment by jerome-pouiller** [comment]
> > Doesn't this happen with the 2's?
> 
> @yonsch I'm not sure what you edited my comment instead of replying in a separate one, but I've just tested building `samples/bluetooth/observer` sample on `efr32bg22_brd4184a` (Series 2 SoC) from the current Zephyr main branch and it compiled without any warnings.

As far as I understand, for the chips based on Cortex-m33, `librail` is compiled with `-mfloat-abi=hard` else, it is compiled with ` -mfloat-abi=softfp`.

**Comment by yonsch** [comment]
@jerome-pouiller 
> As far as I understand, for the chips based on Cortex-m33, `librail` is compiled with `-mfloat-abi=hard` else, it is compiled with ` -mfloat-abi=softfp`.

Both M33 and M4 have a floating point unit, so both can theoretically be used with hard ABI. Looking through the SDK and forums I could only find [this](https://community.silabs.com/s/question/0D51M00007xeNhMSAU/build-error-from-trying-to-turn-on-floating-point-hard-help?language=en_US) comment:

> No Silicon Labs does not supply hardware versions of the libraries except for the Series 2 devices (EFR32MG21, EGR32MG22, etc) which have a different floating point unit.

So as far as I can tell, the correct test is to check which series is used. That doesn't mean it can't change in the future though.

**Comment by jerome-pouiller** [comment]
arf... I have to tell the truth... I have access to the sources of `librail` (and to the build system).

Anyway, it is not a big deal. AFAIK, testing the series or the core will give the exact same result.

**Review by fkokosinski — APPROVED** [review]
LGTM. I'll merge this PR after TSC approves adding these new RAIL blobs: https://github.com/zephyrproject-rtos/zephyr/issues/61109.

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
This is now approved by the TSC @yonsch. Please rebase to fix the conflict.

**Pull request merged**
