### PR TITLE
modules: hal_silabs: Add wfx200 driver and firmware

### PR DESCRIPTION
**Pull request by rvoell-gcx**
This adds the silabs wfx-fullMAC-driver and firmware for wfx200 chips
and modules for use with the wfx200 driver for Zephyr.

This includes a firmware blob from SiLabs. So i think this might needed to be approved.

Origin: SiLabs wfx-fullMAC-driver
License: Apache
URL: https://github.com/SiliconLabs/wfx-fullMAC-driver
commit: 84c8cb0843fe0763eb83c00c6acc423644cdf193
Purpose: Introduction of a wfx200 driver

Signed-off-by: Ruben Völl <ruben.voell@grandcentrix.net>

### CODE REVIEW

**Comment by chrta** [comment]
Thanks for updating. The file `wfx-fullmac-driver/wfx_fmac_driver/firmware/sl_wfx_wf200_C0.h` Contains binary data and a big text block containing license information.
I am not sure about the current state of the inclusion of binary blobs, but i think the type of the blob is fine. But where the blob is allowed to be hosted (within https://github.com/zephyrproject-rtos or within another organization, e.g. https://github.com/SiliconLabs) is afaik in discussion.

**Comment by gcx-dimiz** [comment]
@chrta Is there any progress on this behave? Can this PR made upstream?

**Comment by chrta** [comment]
The zephyr pr https://github.com/zephyrproject-rtos/zephyr/pull/37525 was automatically closed due to inactivity.

I think the biggest issue here is the license in the file `wfx-fullmac-driver/wfx_fmac_driver/firmware/sl_wfx_wf200_C0.h` and the included binary blob. Maybe someone from the TSC could comment here regarding the license in the file and how to include binary blobs.

See e.g. https://docs.zephyrproject.org/latest/contribute/bin_blobs.html

**Comment by gcx-dimiz** [comment]
Yep, I know that https://github.com/zephyrproject-rtos/zephyr/pull/37525 was closed. I'm going to try to push this issue PR further once I got the dev board for the WFM200. 

But I will anyway need to push also this PR further. 

I'm not sure if this west blob approach is suitable here? Because one would need a separate repository for the binary blob and a separate repository for the driver? And both would need to be maintained by Silabs. But I can create a Github issue for the blob to discuss this issue there further?

**Comment by msierszulski** [comment]
Hi @rvoell-gcx
The two PRs mentioned here have been marked as `stale` and closed. Is there any chance to continue this effort? Or should this PR also be closed?

**Comment by rvoell-gcx** [comment]
Hi @msierszulski,
bear with me, that i didn't found the time to continue on this in the past. The good news is, that i recently found some project free space time to work on this again. I will push my work and (re-)open PRs to this and the main repo when i'm back from vacation at the end of august and give it another try to mainline this.

**Comment by fkokosinski** [comment]
Hi @rvoell-gcx! It looks like the file `wfx-fullmac-driver/wfx_fmac_driver/firmware/sl_wfx_wf200_C0.h` contains a firmware binary image. This is not allowed in Zephyr. You need to use the `west blobs` command to download external blobs.

Please take a look at this documentation page: https://docs.zephyrproject.org/latest/contribute/bin_blobs.html.

**Comment by rvoell-gcx** [comment]
Can i add the blob to this PR or should i open a new PR?

**Comment by fkokosinski** [comment]
> Can i add the blob to this PR or should i open a new PR?

You can do it in this PR. No need to open a new one. :)

**Comment by fkokosinski** [comment]
@rvoell-gcx thanks for the update! Looks good. Let's wait for the TSC decision now :)

**Comment by fkokosinski** [comment]
Hi, I've checked the licensing status of files included in this PR, and:
* it looks like the files included in this PR are licensed the same way as in the SiLabs repository (Apache 2.0; e.g. here: https://github.com/SiliconLabs/wfx-fullMAC-driver/blob/master/wfx_fmac_driver/sl_wfx.c)
* the text in the [LRUL.txt](https://github.com/zephyrproject-rtos/hal_silabs/blob/b32d2a2a01483e76bb857f0e3386dc1d27159c67/zephyr/blobs/license/LRUL.txt) file matches the [LICENSE.md](https://github.com/SiliconLabs/wfx-firmware/blob/master/LICENSE.md) file from the SiLabs repo
* the only file licensed under the license from LRUL.txt is the binary blob, so it's not in violation of the Zephyr requirement of using OSI-approved licensed for HAL source code (binary blobs are exempted from it).

**Comment by jerome-pouiller** [comment]
For information, this BLOB is also included in the linux-firmware project:
     https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/wfx/LICENCE.wf200

**Comment by rvoell-gcx** [comment]
I'll probably not gonna continue to work on this.

**Pull request closed without merging**
