### PR TITLE
 modules: hal_silabs: Add Silabs Gecko SDK for EFM32JG12B SoCs 

### PR DESCRIPTION
**Pull request by chrta**
Origin: Silicon Labs Gecko SDK
URL: https://www.silabs.com/products/development-tools/software/simplicity-studio
Version: v5.6.1
Purpose: Add support for Silicon Labs EFM32JG12B SoCs
License: Zlib
Maintained-by: External

Signed-off-by: Christian Taedcke <christian.taedcke@lemonbeat.com>

### CODE REVIEW

**Comment by carlescufi** [comment]
@rettichschnidi could you please review?

**Comment by chrta** [comment]
@Oanerer could you also review, please?

**Comment by Oanerer** [comment]
I won't be able to do a proper review until next week as I'm on vacation now. 

In reply to the question of @mnkp: all header files from SiLabs of SDK version 5.6.1 still show '5.6.0' in the header files, I noticed the same thing for the EFM32GG11B files.

**Comment by chrta** [comment]
> > LGTM, just one question. The included header files embed @version 5.6.0 information. However commit message claims the files are v5.6.1.

> In reply to the question of @mnkp: all header files from SiLabs of SDK version 5.6.1 still show '5.6.0' in the header files, I noticed the same thing for the EFM32GG11B files.

Yes, Silabs does not seem to update the version information for patch versions in their header files. All/Most files that are already checked into master also contain 5.6.0 as version, e.g. https://github.com/zephyrproject-rtos/hal_silabs/blob/master/gecko/Device/SiliconLabs/EFM32WG/Include/efm32wg230f128.h#L5

All the files in this repository are currently from the gecko sdk v5.6.1.

**Comment by mnkp** [comment]
I'm still a bit confused about the versioning information. Seems like a minor thing. However, I need to add support for EFR32BG13P series and I'd like to clarify this. The gecko SDK numbering scheme is different from the version information embedded in the header files. I.e. the 5.6.0 files are provided by Gecko SDK 2.4. That's what I see in my workarea:
```
grep "@version" $SIMPLICITYSTUDIO_V4/developer/sdks/gecko_sdk_suite/v2.?/platform/Device/SiliconLabs/EFM32GG11B/Include/em_device.h
$SIMPLICITYSTUDIO_V4/developer/sdks/gecko_sdk_suite/v2.4/platform/Device/SiliconLabs/EFM32GG11B/Include/em_device.h: * @version 5.6.0
$SIMPLICITYSTUDIO_V4/developer/sdks/gecko_sdk_suite/v2.5/platform/Device/SiliconLabs/EFM32GG11B/Include/em_device.h: * @version 5.7.3
$SIMPLICITYSTUDIO_V4/developer/sdks/gecko_sdk_suite/v2.6/platform/Device/SiliconLabs/EFM32GG11B/Include/em_device.h: * @version 5.8.4
```
As such I'm not sure where the _gecko sdk v5.6.1_ comes from?

**Comment by chrta** [comment]
> As such I'm not sure where the _gecko sdk v5.6.1_ comes from?

When i start Package Manager in SimplicityStudio and let it show the installed versions of SDKs it shows me (below 32 Bit MCU):
32-Bit MCU SDK - 5.6.1.0

When i grep for 5.6.1 in the folder $SIMPLICITYSTUDIO_V4/developer/sdks/gecko_sdk_suite/v2.4 it shows this version in the app folder and also in the file .studio/efm32.properties:
~~~
# EFM32 only properties
id=com.silabs.sdk.exx32
version=5.6.1.0
dependantSdkVersion=2.4.0
label=32-bit MCU SDK
description=Silicon Labs 32-bit MCU SDK for EFM32 and EZR32
supportedParts=mcu.arm.efm32.* mcu.arm.ezr32.*
prop.subLabel=MCU\\ 5.6.1.0
....
~~~

The 5.6.1 originated from the 32-Bit MCU SDK version information visible in the package manager in Simplicity Studio (as far as i remember).

**Comment by mnkp** [comment]
> The 5.6.1 originated from the 32-Bit MCU SDK version information visible in the package manager in Simplicity Studio

I don't have "32-Bit MCU SDK" package installed but I still have all the header files in the installation tree. It's likely these version numbers are not related. I always thought the header files are provided either by "Flex SDK" or "Gecko Platform" package. Their version corresponds to what I see in the installation tree. i.e. gecko_sdk_suite/**v2.4**/platform part. That doesn't seem to be easy to determine. In any case, as long as the header file are coming from `gecko_sdk_suite/v2.4/` sub-tree we should be fine.

**Comment by galak** [comment]
So I wonder if using the CMSIS pack might be easier/more consistent.

https://www.silabs.com/documents/public/cmsis-packs/SiliconLabs.GeckoPlatform_EFM32JG12B_DFP.2.7.0.pack

**Comment by mnkp** [comment]
> So I wonder if using the CMSIS pack might be easier/more consistent.

That's a good idea. However, only the latest Gecko SDK versions seem to be available as packs. Our `gecko/emlib/` got quite old in a meantime. We have version 5.6.0 in tree. Using old emlib with new Gecko SDK / CMSIS packs version is risky (though as I just checked at least for EFR32FG1P it seems to work). It would be best to move everything to the newest version. @chrta it should be probably you or me doing this. As I mentioned I need to add support for EFR32BG13P series so I intended to work on SiLabs hal.

**Comment by chrta** [comment]
I would also prefer to use a source for this sdk that does not require to install an ide to get it. So using the pack would be fine for me.

But we have to consider how we want to add devices later on. It should be possible to get the older versions of the packs to use the same version for all devices in this repo without the need to upgrading everything to add just one device.

@mnkp There is still the discussion open on how to use the rails sdk (that depends on this gecko sdk), see https://github.com/zephyrproject-rtos/zephyr/issues/17005 Silabs changed the license in the newest version of the sdk in the header files, the license of the binary blob ist still open. The question is should be wait with an sdk upgrade for this or just do it now? I would be fine with both.

Can we move this discussion to a issue, so this code here can be merged?

**Comment by chrta** [comment]
@mnkp 
> Their version corresponds to what I see in the installation tree. i.e. gecko_sdk_suite/v2.4/platform part.

The version scheme and packaging of the gecko sdk changed over time. The initial version imported into zephyr was version 5.1.2 and imported from github https://github.com/SiliconLabs/Gecko_SDK/tree/v5.1.2 This was quite easy. Since this repository is no longer maintained, the newer versions had to be downoaded from somewhere else.

**Comment by galak** [comment]
Does it make sense to document in the README things on a per family/import basis?  I think the CMSIS pack I pointed out would be a reasonable case to use as the first one to split out.  Thoughts?

**Comment by chrta** [comment]
> Does it make sense to document in the README things on a per family/import basis?

Yes, maybe we have to extend the readme for different families. It seems that it is a little bit different for the wireless SOCS (EFR32), since also the installation package in the Simplicity Studio is named different (not "32-Bit MCU SDK", but "Flex SDK" or even something else).

> I think the CMSIS pack I pointed out would be a reasonable case to use as the first one to split out. Thoughts?

I think there are version dependecies between the CMSIS pack things and the emlib (which is not part of the pack). Until this is sorted out, i would not add this to the README.
Also i do not like that only the most up to date CMSIS pack is available.

I would suggest that @mnkp and me try to figure this out, maybe with the help of someone from Silabs like @conq. Things to solve:
* [ ] what are the possible/preffered sources for CMSIS device files and the emlib?
* [ ] how can we ensure version compatibility between them?
* [ ] what version information should we use to identify the version of the files in this hal (2.4 vs 5.6.1.0)?
* [ ] update README accordingly
* [ ] update this hal to the most recent version using the documented way

**Comment by galak** [comment]
Sounds good to me.  I'm going to merge this so we can make progress on this SoC support while you work on those issues.

**Comment by mnkp** [comment]
@chrta thanks, the proposal sounds good. 

To sum up: let's try to move to using CMSIS packs but first figure the proper way to do it. I'll try to get the answers from my contact at SiLabs unless @conq answers first. For now let's continue the way we've been doing it and stick to files in `$SIMPLICITYSTUDIO_V4/developer/sdks/gecko_sdk_suite/v2.4/platform/Device/`.

> Also i do not like that only the most up to date CMSIS pack is available.

That's indeed not ideal. SiLabs, provides updates to their hals quite often. On the other hand it would force us to keep hals reasonably up to date.

**Comment by galak** [comment]
> > Also i do not like that only the most up to date CMSIS pack is available.
> 
> That's indeed not ideal. SiLabs, provides updates to their hals quite often. On the other hand it would force us to keep hals reasonably up to date.

I think its an issue for other vendors, wish they kept old versions around and just had git trees ;)

**Comment by conq** [comment]
We (Silicon Labs) are currently working on what to do about this. I'm advocating for putting all of our platform code on github so that it can be easily submodules into projects like Zephyr. 

(The release number mismatch is most likely an issue with our arcane release/versioning system).

**Pull request merged**
