### PR TITLE
modules: hal_silabs: Update SiLabs Gecko HAL to version 2.7.3

### PR DESCRIPTION
**Pull request by mnkp**
Both device header files and emlib are updated to the new version.

Note: version number reflects the new versioning scheme introduced by
Silicon Labs.

Origin: Silicon Labs Gecko SDK
URL: https://www.silabs.com/products/development-tools/software/simplicity-studio
Version: 2.7.3
Purpose: Add support for Silicon Labs SoCs
License: Zlib
Maintained-by: External

### CODE REVIEW

**Comment by galak** [comment]
Zephyr PR related to this?

**Comment by mnkp** [comment]
@chrta thanks for the report. I did overlook the fact that I need to patch some files. This is done now.

I've tested the new HAL with a few sample applications + our own rail based application. All was working well. However, the watchdog sample fails indeed (tested on efr32_slwstk6061a board). It seems like the clock signal the WDOG module is supposed to run on is not there. I will have to look a bit more into this.

**Comment by mnkp** [comment]
I solved the watchdog issue. The driver relied on the default configuration provided by SiLabs via `WDOG_INIT_DEFAULT` define. The default clock has been changed from ULFRCO to LFRCO in between SiLabs HAL versions. The fix is in the Zephyr repo.

**Comment by mnkp** [comment]
@galak Could we merge this one?

**Pull request merged**
