### PR TITLE
modules: hal_silabs: Add support for EFR32MG24B220F1536IM48 SoC

### PR DESCRIPTION
**Pull request by mrfuchs**
Add HAL components required for adding xG24-RB4187C board support in Zephyr.

As the RB4187C is a plug-in board to the Wireless Gecko Pro Kit Mainboard, an additional fix is needed for the common efr32_radio board. In this case, CONFIG_BOARD (e.g. efr32_radio_brd4180a) does not match the board directory name (efr32_radio) and including the board directory will fail. Fix this by passing the BOARD_DIR variable to zephyr_include_directories() instead.

### CODE REVIEW

**Comment by fkokosinski** [comment]
Hi @mrfuchs, thanks for this PR. Could you list in-tree boards that are affected by this? Also, could you create a PR in Zephyr that uses the changes that you're introducing in this PR so that they can be verified in CI?

**Comment by mrfuchs** [comment]
Hi @fkokosinski, the current in-tree efr32_radio boards (brd4104a, brd4180a, brd4250b and brd4255a) are not really affected because they do not have header files in their board directory. That's probably why nobody noticed that the directory include for the efr32_radio (main) board is wrong.
When adding support for the brd4187c (plug-in) board to efr32_radio, I had to add the `sl_device_init_hfxo_config.h` file (like you did in zephyrproject-rtos/zephyr#55092) to the board directory which could not be found due to this issue.

I'll create a PR for brd4187c as soon as your [PR](https://github.com/zephyrproject-rtos/zephyr/pull/55092) is merged as my code depends on your work re. the EFR32MG24 SoC.
If the fix in this PR cannot be merged without having an associated Zephyr PR, I'll add a second commit to it that adds the device header file (efr32mg24b220f1536im48.h). What do you prefer?

**Comment by fkokosinski** [comment]
> I'll create a PR for brd4187c as soon as your [PR](https://github.com/zephyrproject-rtos/zephyr/pull/55092) is merged as my code depends on your work re. the EFR32MG24 SoC. If the fix in this PR cannot be merged without having an associated Zephyr PR, I'll add a second commit to it that adds the device header file (efr32mg24b220f1536im48.h). What do you prefer?

Hi @mrfuchs 

What do you mean that it depends on it? In general you don't need to create PRs changing more than just the `west.yml`, where you make it point to this PR, i.e. you set the `revision` field in `hal_silabs` to `pull/24/head`.

If you really need your changes to make it work (compile in the CI):
* create a PR
* add to the description relevant info, e.g. which PR it depends on, which commits are to be dropped once your dependencies are merged
* mark it as a draft

**Comment by fkokosinski** [comment]
@mrfuchs FYI the MG24 PR is now merged.

**Review by fkokosinski — APPROVED** [review]
LGTM

**Pull request merged**
