### PR TITLE
modules: hal_silabs: Import sleeptimer service

### PR DESCRIPTION
**Pull request by thorvald**
Allows using the RTC, RTCC or BURTC for low-energy system timers

Signed-off-by: Thorvald Natvig <thorvald@natvig.com>

### CODE REVIEW

**Comment by thorvald** [comment]
See https://github.com/zephyrproject-rtos/zephyr/pull/29201 for matching PR

**Comment by chrta** [comment]
Hmm, i think we should also update the rest of the HAL to version 3 in a separate pr. This way every file in this repo would be from the same version.
I general this looks good to me, but i want to test this before approving it.

**Comment by chrta** [comment]
I am in the process of upgrading the complete HAL to version 3.1.0. After it is finished and merged, this pr should be rebased and also use gecko sdk 3.1.0. This way we prevent a mixture of different versions.

**Comment by thorvald** [comment]
Sounds good :)

**Comment by chrta** [comment]
Closing this because no activity more than 6 months and the corresponding pr in zephyr is also closed due to inactivity.

**Pull request closed without merging**
